---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyr)
library(dplyr)
```

Rent = total+area_type+dwelling_type+kitchen+water+sanitation+commute

[1] "NSS_region"             "mpce_quintile"          "occupation_group"       "hh_skill_group"         "housing_unit_type"      "commute"               
 [7] "commute_cat"            "area_cat"               "dw_access_recoded"      "tenure_status"          "latrine_access_recoded" "is_couple_noroom"      
[13] "Social_group"           "commute_glm" 

```{r}

glm_data=recode_percapitaarea_cat(recode_marrie_couple_room(recode_latrine_access(recode_tenure_status(recode_dw_access(recode_area_cat(recode_commute_cat(recode_dwelling_room(house_cat_base_data))))))))%>%
  select(10,82:95,55,37)

glm_data=glm_data %>%
  #filter(commute_cat!="Not Working")%>%
  mutate(commute_glm=if_else(commute_cat %in% c("No Commute","Upto 5 Km"),1,0),
         urban_poor_glm=if_else(mpce_quintile %in% c(1,2),"Urban_Poor","Not_poor"),
         couple_noroom_glm=if_else(is_couple_noroom==1,"No","Yes"),
         percapitaarea_cat_glm=as.numeric(percapitaarea_cat),
         Social_group_glm=as.factor(Social_group))

```



```{r}

glm_1=glm(data = glm_data, 
          commute_glm~urban_poor_glm+
            occupation_group+
            couple_noroom_glm+
            age_cat+
            Social_group_glm,
          family = "binomial")

summary(glm_1)
VIF(glm_1)
visreg::visreg(glm_1,"occupation_group",gg=TRUE,scale = "response")
visreg::visreg(glm_1,"Social_group_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_1,"urban_poor_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_1,"age_cat",gg=TRUE,scale = "response")
visreg::visreg(glm_1,"couple_noroom_glm",gg=TRUE,scale = "response")
```



```{r}
glm_2=glm(data = glm_data, 
          percapitaarea_cat_glm~urban_poor_glm+
            occupation_group+
            couple_noroom_glm+
            age_cat+
            Social_group_glm,
          family = "binomial")

summary(glm_2)
VIF(glm_2)
visreg::visreg(glm_2,"occupation_group",gg=TRUE,scale = "response")
visreg::visreg(glm_2,"Social_group_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_2,"urban_poor_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_2,"age_cat",gg=TRUE,scale = "response")
visreg::visreg(glm_2,"couple_noroom_glm",gg=TRUE,scale = "response")

```



```{r}
glm_data=glm_data%>% mutate(tenure_status_glm=if_else(tenure_status=="Ownership",1,0))
glm_3=glm(data = glm_data, 
          tenure_status_glm~urban_poor_glm+
            occupation_group+
            couple_noroom_glm+
            age_cat+
            Social_group_glm,
          family = "binomial")

summary(glm_3)
VIF(glm_3)
visreg::visreg(glm_3,"occupation_group",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"Social_group_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"urban_poor_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"age_cat",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"couple_noroom_glm",gg=TRUE,scale = "response")
```


```{r}
glm_data=glm_data%>% mutate(tenure_status_glm=if_else(tenure_status=="Formal Rental",1,0))
glm_3=glm(data = glm_data, 
          tenure_status_glm~urban_poor_glm+
            occupation_group+
            couple_noroom_glm+
            age_cat+
            Social_group_glm,
          family = "binomial")

summary(glm_3)
VIF(glm_3)
visreg::visreg(glm_3,"occupation_group",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"Social_group_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"urban_poor_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"age_cat",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"couple_noroom_glm",gg=TRUE,scale = "response")
```

```{r}
glm_data=glm_data%>% mutate(tenure_status_glm=if_else(tenure_status=="Informal Rental",1,0))
glm_3=glm(data = glm_data, 
          tenure_status_glm~urban_poor_glm+
            occupation_group+
            couple_noroom_glm+
            age_cat+
            Social_group_glm,
          family = "binomial")

summary(glm_3)
VIF(glm_3)
visreg::visreg(glm_3,"occupation_group",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"Social_group_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"urban_poor_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"age_cat",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"couple_noroom_glm",gg=TRUE,scale = "response")
```


```{r}
glm_data=glm_data%>% mutate(tenure_status_glm=if_else(tenure_status=="Others",1,0))
glm_3=glm(data = glm_data, 
          tenure_status_glm~urban_poor_glm+
            occupation_group+
            couple_noroom_glm+
            age_cat+
            Social_group_glm,
          family = "binomial")

summary(glm_3)
VIF(glm_3)
visreg::visreg(glm_3,"occupation_group",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"Social_group_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"urban_poor_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"age_cat",gg=TRUE,scale = "response")
visreg::visreg(glm_3,"couple_noroom_glm",gg=TRUE,scale = "response")
```

```{r}
glm_data=glm_data%>% mutate(dw_access_glm=if_else(dw_access_recoded=="Exclusive",1,0))
glm_4=glm(data = glm_data, 
          dw_access_glm~urban_poor_glm+
            occupation_group+
            couple_noroom_glm+
            age_cat+
            Social_group_glm,
          family = "binomial")

summary(glm_4)
VIF(glm_4)
visreg::visreg(glm_4,"occupation_group",gg=TRUE,scale = "response")
visreg::visreg(glm_4,"Social_group_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_4,"urban_poor_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_4,"age_cat",gg=TRUE,scale = "response")
visreg::visreg(glm_4,"couple_noroom_glm",gg=TRUE,scale = "response")
library(car)
leveneTest(dw_access_glm~age_cat,data = glm_data)
summary(aov(dw_access_glm~age_cat,data = glm_data))

```

```{r}
glm_data=glm_data%>% mutate(dw_access_glm=if_else(dw_access_recoded=="Shared",1,0))
glm_4=glm(data = glm_data, 
          dw_access_glm~urban_poor_glm+
            occupation_group+
            couple_noroom_glm+
            Social_group_glm,
          family = "binomial")

summary(glm_4)
VIF(glm_4)
visreg::visreg(glm_4,"occupation_group",gg=TRUE,scale = "response")
visreg::visreg(glm_4,"Social_group_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_4,"urban_poor_glm",gg=TRUE,scale = "response")
visreg::visreg(glm_4,"couple_noroom_glm",gg=TRUE,scale = "response")

anova(glm_4)
```

