values_areatype= c("1"="#D0AD5E", "2"="#6dab6b",'3'="#989B5C","9"="#006666")
values_commute=c("No Commute"="#D0AD5E","Upto 5 Km"="#006666","5 to 10 Km"="#6dab6b","More than 10Km"="#5C899B","Not Working"="#989B5C")
values_floor= c("Single Floor"="#D0AD5E", "Multi_Floor"="#006666")
values_housetype= c("1"="#D0AD5E", "2"="#6dab6b","9"="#006666")
values_maritalstatus= c("1"="#D0AD5E", "2"="#6dab6b","3"="#006666")
values_wall= c("Kacha"="#D0AD5E", "Pucca"="#6dab6b")
values_roof= c("Temporary"="#D0AD5E", "Semi_Permanent"="#6dab6b","Permanent"="#006666")
values_water= c("Exclusive"="#D0AD5E", "Shared"="#6dab6b","Public"="#006666","Others"="#5C899B")
values_latrine= c("Exclusive"="#D0AD5E", "Shared"="#6dab6b","Public"="#006666","No_Toilet"="#5C899B")
values_kitchentype= c("1"="#D0AD5E", "2"="#6dab6b","3"="#006666")


limits_areatype = c("1", "2","3","9")
limits_floor = c("Single Floor", "Multi_Floor")
limits_housetype = c("1", "2", "9")
limits_maritalstatus = c("1", "2", "3")
limits_kitchentype = c("1", "2", "3")
limits_latrine = c("Exclusive", "Shared","Public","No_Toilet")
limits_water = c("Exclusive", "Shared","Public","Others")
limits_roof= c("Temporary", "Semi_Permanent","Permanent")
limits_wall=c("Kacha","Pucca")


labels_areatype = c("Notified Slum", "Non-Notified Slum", "Squatter","Non-Slum")
labels_floor = c("Single Floor", "Multi Floor")
labels_housetype = c("Independent", "Flat", "Others")
labels_maritalstatus = c("All", "Some", "No Married Couuple")
labels_kitchentype = c("Kitchen with Water", "Kitchen without water", "No Kitchen")
labels_latrine = c("Exclusive", "Shared","Public","No Toilet")
labels_water = c("Exclusive", "Shared","Public","Others")
labels_roof= c("Temporary", "Semi Permanent","Permanent")
labels_wall=c("Kacha","Pucca")
